### ISSUE TITLE
timestamping when online logging

### ISSUE THREAD

**Issue by onihound** [jtcash/OwonB41T#2]
Hello
I'm using your piece of software and very happy with it: I have some troubles with my power provider and have to proove the undervoltage on my own.

I was wondering if you could add the timestamp when online logging, so we can keep a track of the evolution with time.

I do have this kind of information when appending to file : 
-> 231.1;V AC;AUTO;f061 0004 0907 

I was wondering what could be the last field (**f061 0004 0907**) and tried to use a hex to time tool, but it does not seem to match.

So I'm raising that idea to be able to have a human readable (or at lease unix time-like) date/time field, would be great !

Thanks

Vincent

**Comment by art-ya** [comment]
Hi Vincent! I had the same need - to output the measurement time. But I take the time from the PC, not from the multimeter. 
The result is a csv file like this:
![image](https://user-images.githubusercontent.com/92534535/147061966-4168af83-a983-4568-997c-d85d0747912b.png)
The first three columns are the date, time and number of milliseconds.
If that suits you, I can send you the code.
Sincerely, Artem

**Comment by onihound** [comment]
Hi there

if you have the code, yep, interested ;)
thanks so much !

Vincent

**Comment by art-ya** [comment]
https://github.com/art-ya/OwonB41T
I uploaded the code here

**Comment by onihound** [comment]
cool, many thanks :) 
Closing this issue, thank you very much for your time ;)

**Comment by onihound** [comment]
extra code given to fullfill the original request
